### PR TITLE
feat: support ppc64le and riscv64

### PR DESCRIPTION
**Pull request by Desiki-high**
Ref: https://github.com/dragonflyoss/nydus/pull/1510.
---
Add `BASE_MAGIC_ID` in ppc64le and riscv64 archs.

### CODE REVIEW

**Comment by imeoer** [comment]
Maybe we need also to add the test jobs for powerpc64 and riscv64 in github action.

**Comment by Desiki-high** [comment]
> Maybe we need also to add the test jobs for powerpc64 and riscv64 in github action.

Add test in `amd64`, `arm64`, `ppc64le`, `riscv64`.

**Comment by Desiki-high** [comment]
PTAL @bergwolf, Thanks.

**Review by imeoer — APPROVED** [review]
We'd better contribute it to https://github.com/firecracker-microvm/firecracker/tree/main/src/snapshot as well, but it seems that firecracker doesn't support ppc64le and riscv64 yet.

**Comment by Desiki-high** [comment]
> We'd better contribute it to https://github.com/firecracker-microvm/firecracker/tree/main/src/snapshot as well, but it seems that firecracker doesn't support ppc64le and riscv64 yet.

I will try it, maybe the maintainers of https://github.com/firecracker-microvm/firecracker have some other considerations.

**Comment by Desiki-high** [comment]
I have contributed it to https://github.com/firecracker-microvm/firecracker in https://github.com/firecracker-microvm/firecracker/pull/4319. Can we merge this and release it first? Because firecracker doesn't support `ppc64le` and `riscv64`, we need this. cc @imeoer .

**Comment by Desiki-high** [comment]
See https://github.com/firecracker-microvm/firecracker/pull/4319#issuecomment-1853649851, we can only use this in our fork crate.

**Comment by imeoer** [comment]
@bergwolf It seems the CI hang on "Waiting for status to be reported", is the setting correct?

**Review by jiangliu — APPROVED** [review]

**Pull request merged**
